language: objective-c
os: osx
podfile: Example/Podfile
osx_image: xcode7

before_script:
  - gem install xcpretty
  - gem install cocoapods -N

script:
  - xcodebuild -workspace Example/Yashin.xcworkspace -scheme Yashin_Tests -destination 'platform=iOS Simulator,name=iPhone 6s Plus' test 
