language: objective-c
os: osx
osx_image: xcode7

before_script:
  - gem install xcpretty

script:
  - xcodebuild -workspace Example/Yashin.xcworkspace -scheme Yashin_Tests -destination 'platform=iOS Simulator,name=iPhone 6s Plus' test 
